name: jsDelivr Cache Purging
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      alias:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Alias to purge'
        # Default value if no value is explicitly provided
        default: '0'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
    - name: curl purging
      uses: wei/curl@v1.1.1
      with:
        args: -X POST http://purge.jsdelivr.net -H 'cache-control:\ no-cache' -H 'content-type:\ application/json' -d '{"path":["/npm/@alixlahuec/zotero-roam@${{ github.event.inputs.version }}"]}'
